version: "3"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks: 
      - isucon
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: xsuportal
      MYSQL_ROOT_PASSWORD: isucon
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ".:/tmp/isucon"
    networks: 
      - isucon
networks: 
  isucon:
    driver: bridge
