version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isuumo
      MYSQL_ROOT_PASSWORD: isucon
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ".:/tmp/isucon"

